server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379

  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/product-service/**