server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8001
          predicates:
            - Path=/auth-service/**
        - id: coupon-service
          uri: http://localhost:8002
          predicates:
            - Path=/coupon-service/**