version: '3.7'
services:
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis-server
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    ports:
      - 6379:6379